config/routes.rb
BootstrapApp::Application.routes.draw do
  root :to => "home#index"

  devise_for :users, :controllers => {
    registrations: "users/registrations",
    passwords: "users/passwords",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  get '/game/:slug' => 'games#show'

  get '/unfollow/user/:slug' => 'users#unfollow_user', as: :user_unfollow
  get '/follow/user/:slug' => 'users#follow_user', as: :user_follow
  get '/user/profile/edit' => 'users#edit_profile'
  post '/user/profile/update' => 'users#update_profile'

  post     '/posts'             => 'posts#create'
  get      '/posts/events'      => 'posts#events', as: 'event_post'
  get      '/posts/notify'      => 'posts#notify', as: 'notify_post'
  get      '/posts/new'         => 'posts#new'
  get      '/posts/feed'        => 'posts#feed', as: 'feed'
  get      '/posts/:slug/edit'  => 'posts#edit', as: 'edit_post'
  get      '/posts/:slug'       => 'posts#show', as: 'post'
  patch    '/posts/:slug'       => 'posts#update'
  put      '/posts/:slug'       => 'posts#update'
  delete   '/posts/:slug'       => 'posts#destroy'
  post     '/posts/:slug/like'  => 'posts#like', as: 'like_post'

  get '/:slug' => 'users#show'
end

app/views/shared/_footer.html.erb
<footer id="footer">
  <div class="container">
    <div class="row info">
      <div class="span6 residence">
        <ul>
          <li>2301 East Lamar Blvd. Suite 140. City, Arlington.</li>
          <li>United States, Zip Code TX 76006.</li>
        </ul>
      </div>
      <div class="span5 touch">
        <ul>
          <li><strong>P.</strong> 1 817 274 2933</li>
          <li><strong>E.</strong><a href="#"> bootstrap@twitter.com</a></li>
        </ul>
      </div>
    </div>
    <div class="row credits">
      <div class="span12">
        <div class="row social">
          <div class="span12">
            <a href="#" class="facebook">
              <span class="socialicons ico1"></span>
              <span class="socialicons_h ico1h"></span>
            </a>
            <a href="#" class="twitter">
              <span class="socialicons ico2"></span>
              <span class="socialicons_h ico2h"></span>
            </a>
            <a href="#" class="gplus">
              <span class="socialicons ico3"></span>
              <span class="socialicons_h ico3h"></span>
            </a>
            <a href="#" class="flickr">
              <span class="socialicons ico4"></span>
              <span class="socialicons_h ico4h"></span>
            </a>
            <a href="#" class="pinterest">
              <span class="socialicons ico5"></span>
              <span class="socialicons_h ico5h"></span>
            </a>
            <a href="#" class="dribble">
              <span class="socialicons ico6"></span>
              <span class="socialicons_h ico6h"></span>
            </a>
            <a href="#" class="behance">
              <span class="socialicons ico7"></span>
              <span class="socialicons_h ico7h"></span>
            </a>
          </div>
        </div>
        <div class="row copyright">
          <div class="span12">
            © 2013 Clean Canvas. All rights reserved. Theme by Detail Canvas.
          </div>
        </div>
      </div>            
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container-fluid">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <%= link_to "GAME SITE", root_path, :class => 'brand' %>
      <input type="text" class="input-large search-query pull-left" placeholder="Search">
      <ul class="nav pull-right">
        <% if user_signed_in? %>
          <li><%= link_to 'Edit account', edit_user_registration_path, method: 'get' %></li>
          <li><%= link_to 'Sign out', destroy_user_session_path, method: 'delete' %></li>
        <% else %>
          <li><%= link_to 'Sign up', new_user_registration_path %></li>
          <li><%= link_to 'Sign in', user_session_path %></li>
          <li><%= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook) %></li>
          <li><%= link_to "Sign in with Twitter", user_omniauth_authorize_path(:twitter) %></li>
        <% end %>
      </ul>
    </div>
  </div>
</header>

app/views/shared/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : name %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/shared/_sidebar.html.erb
<aside class="span3">
  <div class="well sidebar-nav">
    <h3><%= current_user.username %></h3>
    <span><%= link_to "Edit Profile", user_profile_edit_path %></span>
    <ul class="nav nav-list">
      <li class="nav-header">Sidebar</li>
      <!-- sidebar menu models -->
      <li><%= link_to "Link1", "/path1"  %></li>
      <li><%= link_to "Link2", "/path2"  %></li>
      <li><%= link_to "Link3", "/path3"  %></li>
    </ul>
  </div><!--/.well -->
</aside>