config/routes.rb
BootstrapApp::Application.routes.draw do
  root :to => "home#index"

  devise_for :users, :controllers => {
    registrations: "users/registrations",
    passwords: "users/passwords",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  get '/game/:slug' => 'games#show'

  get '/unfollow/user/:slug' => 'users#unfollow_user', as: :user_unfollow
  get '/follow/user/:slug' => 'users#follow_user', as: :user_follow
  get '/user/profile/edit' => 'users#edit_profile'
  post '/user/profile/update' => 'users#update_profile'

  post     '/posts'             => 'posts#create'
  get      '/posts/events'      => 'posts#events', as: 'event_post'
  get      '/posts/notify'      => 'posts#notify', as: 'notify_post'
  get      '/posts/new'         => 'posts#new'
  get      '/posts/feed'        => 'posts#feed', as: 'feed'
  get      '/posts/:slug/edit'  => 'posts#edit', as: 'edit_post'
  get      '/posts/:slug'       => 'posts#show', as: 'post'
  patch    '/posts/:slug'       => 'posts#update'
  put      '/posts/:slug'       => 'posts#update'
  delete   '/posts/:slug'       => 'posts#destroy'
  post     '/posts/:slug/like'  => 'posts#like', as: 'like_post'

  get '/:slug' => 'users#show'
end

app/models/game.rb
class Game
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Search

  field :title, type: String
  field :publish_date, type: DateTime
  field :slug, type: String
  field :gbd_id, type: Integer
  field :overview, type: String
  field :esrb, type: String
  field :players, type: String
  field :cooperative, type: String
  field :publisher, type: String
  field :developer, type: String
  field :release_date, type: DateTime
  field :rating, type: String
  field :youtube_video, type: String
  field :genres, type: String

  validates :title, uniqueness: true, presence: true
  validates :slug, uniqueness: true, presence: true
  before_validation :generate_slug
  has_and_belongs_to_many :platforms

  search_in :title

  def to_s
    title
  end

  def to_param
    slug
  end

  def generate_slug
    self.slug ||= self.title.parameterize
  end

  def self.add_game(game)
    created_game = self.create({
      gbd_id: game.gbd_id,
      title: game.title,
      overview: game.overview,
      esrb: game.esrb,
      players: game.players,
      cooperative: game.cooperative,
      publisher: game.publisher,
      developer: game.developer,
      release_date: (game.release_date rescue nil),
      rating: game.rating,
      youtube_video: game.youtube_video,
      genres: game.genres
    })
    if created_game.errors.messages.blank?
      Platform.find_or_create_by(name: game.platform).games << created_game
    end
  end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show]

  # GET /games/:slug
  def show
  end


  private
  # Use callbacks to share common setup or constraints between actions.
  def set_game
    @game ||= Game.where(slug: params[:slug]).first
  end

end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= simple_form_for(@game) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :show %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<h1>Listing games</h1>

<table>
  <thead>
    <tr>
      <th>Show</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= game.show %></td>
        <td><%= link_to 'Show', game %></td>
        <td><%= link_to 'Edit', edit_game_path(game) %></td>
        <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game', new_game_path %>

app/views/games/new.html.erb
<h1>New game</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<p>
  <strong>Show:</strong>
  <h1><%= @game %></h1>
</p>